name: Build
on:
  # Trigger the workflow on pushes to only the 'master' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [main, dev]
  # Trigger the workflow on any pull request
  pull_request:

jobs:

  glibc:
    name: Build & Test with glibc
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      # Install tools
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      - name: build-test
        run: |
          podman build -f build-glibc.Dockerfile -t local/glibc .
          podman images
          ./extract-executables.sh local/glibc -o out/glibc
          ls -lA out/glibc
      
  dietlibc:
    name: Build & Test with dietlibc
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      # Install tools
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      - name: build-test
        run: |
          podman build -f build-dietlibc.Dockerfile -t local/dietlibc .
          podman images
          ./extract-executables.sh local/dietlibc -o out/dietlibc
          ls -lA out/dietlibc
      
  musl:
    name: Build & Test with musl
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      # Install tools
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      - name: build-test
        run: |
          podman build -f build-musl.Dockerfile -t local/musl .
          podman images
          ./extract-executables.sh local/musl -o out/musl
          ls -lA out/musl
