name: Full Test

# This build takes a VERY long time to run.  Only run on-demand.
on:
  push:
    branches: [main]

jobs:

  glibc:
    name: Full Build & Test with glibc
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      # Install tools
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      - name: build-test
        run: |
          podman build -f build-glibc.Dockerfile -t glibc:offline --build-arg BUILD_MODE=full-test .
      # Podman on Ubuntu is a buggy version that causes this to look up the
      # image online, rather than look in the local repo.
      # https://github.com/containers/podman/issues/11181
      # podman images
      # ./extract-executables.sh localhost/glibc:offline -o out/glibc
      # ls -lA out/glibc

  dietlibc:
    name: Full Build & Test with dietlibc
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      # Install tools
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      - name: build-test
        run: |
          podman build -f build-dietlibc.Dockerfile -t dietlibc:offline --build-arg BUILD_MODE=full-test .
      
  musl:
    name: Full Build & Test with musl
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      
      # Install tools
      - name: Install Required tools
        run: |
          sudo apt-get update
          sudo apt-get install podman
      
      - name: build-test
        run: |
          podman build -f build-musl.Dockerfile -t musl:offline --build-arg BUILD_MODE=full-test .
